[
  {
    _id: "sad87da79",
    title: "Title_1",
    company: "Company_1",
    companyWebsite: "companywebsite.com_1",
    location: "Location_1",
    jobTitle: "JobTitle_1",
    description: "Description_1",
    startDate: "01/01/2000",
    endDate: "01/01/2020",
  },
  {
    _id: "sad87da79",
    title: "Title_2",
    company: "Company_2",
    companyWebsite: "companywebsite.com_2",
    location: "Location_2",
    jobTitle: "JobTitle_2",
    description: "Description_2",
    startDate: "01/01/2002",
    endDate: "01/01/2020",
  },
  {
    _id: "sad87da79",
    title: "Title_3",
    company: "Company_3",
    companyWebsite: "companywebsite.com_3",
    location: "Location_3",
    jobTitle: "JobTitle_3",
    description: "Description_3",
    startDate: "01/01/2003",
    endDate: "01/01/2020",
  },
];
